# Generated by Django 5.0.14 on 2026-03-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Diyetisyen Aylin Balkan', max_length=200, verbose_name='Diyetisyen Adı')),
                ('title', models.CharField(default='Uzman Diyetisyen', max_length=200, verbose_name='Unvan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='diet/logos/', verbose_name='Kurumsal Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Sitesi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='İletişim Numarası')),
            ],
            options={
                'verbose_name': 'Diyetisyen Profili',
                'verbose_name_plural': 'Diyetisyen Profili',
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='diet/logos/', verbose_name='Diyetisyen Logosu / Banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('target_calories', models.PositiveIntegerField(default=2000, verbose_name='Hedef Enerji (kcal)')),
                ('target_carb_percent', models.PositiveIntegerField(default=50, verbose_name='Hedef CHO %')),
                ('target_prot_percent', models.PositiveIntegerField(default=20, verbose_name='Hedef Prot %')),
                ('target_fat_percent', models.PositiveIntegerField(default=30, verbose_name='Hedef Yağ %')),
            ],
            options={
                'verbose_name': 'Diyet Planı',
                'verbose_name_plural': 'Diyet Planları',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kategori Açıklaması')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='diet/icons/', verbose_name='Kategori İkonu')),
            ],
            options={
                'verbose_name': 'Besin Kategorisi',
                'verbose_name_plural': 'Besin Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Ölçü Birimi (Örn: Dilim, Adet, Kase)')),
            ],
            options={
                'verbose_name': 'Ölçü Birimi',
                'verbose_name_plural': 'Ölçü Birimleri',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('height', models.PositiveIntegerField(verbose_name='Boy (cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kilo (kg)')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='Cinsiyet')),
                ('activity_level', models.DecimalField(decimal_places=2, default=1.2, max_digits=3, verbose_name='Aktivite Katsayısı (1.2-1.9)')),
            ],
            options={
                'verbose_name': 'Danışan',
                'verbose_name_plural': 'Danışanlar',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarif Adı')),
                ('instructions', models.TextField(verbose_name='Hazırlanış Metni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diet/recipes/', verbose_name='Tarif Görseli')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube Linki')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('0_UYANINCA', 'Uyanınca Ara Öğünü'), ('1_KAHVALTI', 'Kahvaltı'), ('2_KAH_SONRASI', 'Kahvaltı Sonrası Ara Öğün'), ('3_OGLE_ONCESI', 'Öğle Öncesi Ara Öğün'), ('4_OGLE', 'Öğle Yemeği'), ('5_OGLE_SONRASI', 'Öğle Sonrası Ara Öğün'), ('6_AKSAM_ONCESI', 'Akşam Öncesi Ara Öğün'), ('7_AKSAM', 'Akşam Yemeği'), ('8_AKSAM_SONRASI', 'Akşam Sonrası Ara Öğün'), ('9_GECE', 'Gece Öğünü')], max_length=20, verbose_name='Öğün Tipi')),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='diet/meals/', verbose_name='Öğün Görseli (Opsiyonel)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Öğün Notları')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietplan', verbose_name='Diyet Planı')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Besin', max_length=200, verbose_name='Besin Adı')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kalori (kcal)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Karbonhidrat (g)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protein (g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g)')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.meal', verbose_name='Öğün')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
            ],
            options={
                'verbose_name': 'Öğün Besini',
                'verbose_name_plural': 'Öğün Besinleri',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Besin Adı')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kalori (kcal)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Karbonhidrat (g)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Protein (g)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Yağ (g)')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
            ],
            options={
                'verbose_name': 'Besin',
                'verbose_name_plural': 'Besinler',
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='diet.patient', verbose_name='Danışan'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Malzeme', max_length=200, verbose_name='Besin Adı')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kalori (kcal)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Karbonhidrat (g)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protein (g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g)')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='diet.recipe', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
            },
        ),
        migrations.CreateModel(
            name='RecipeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kalori (kcal)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Karbonhidrat (g)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protein (g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g)')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='diet.recipe', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'Tarif Ölçü Birimi',
                'verbose_name_plural': 'Tarif Ölçü Birimleri',
            },
        ),
        migrations.CreateModel(
            name='MealRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ölçü Miktarı (Çarpan)')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.meal', verbose_name='Öğün')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipemeasure', verbose_name='Tarif Ölçüsü')),
            ],
            options={
                'verbose_name': 'Öğün Tarifi',
                'verbose_name_plural': 'Öğün Tarifleri',
            },
        ),
    ]
