# Generated by Django 5.0.14 on 2026-03-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipe',
            name='recipe_measure',
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Tarif Malzemesi', 'verbose_name_plural': 'Tarif Malzemeleri'},
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kalori (kcal)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Karbonhidrat (g)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protein (g)'),
        ),
        migrations.DeleteModel(
            name='RecipeMeasure',
        ),
    ]
