# Generated by Django 5.0.14 on 2026-03-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_remove_mealrecipe_recipe_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Grup Adı. (Örn: Süt, Et, Meyve)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Karbonhidrat (g)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Protein (g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g)')),
            ],
            options={
                'verbose_name': 'Besin Grubu (Değişim)',
                'verbose_name_plural': 'Besin Grupları',
            },
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.AddField(
            model_name='food',
            name='food_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.foodgroup', verbose_name='Besin Grubu'),
        ),
    ]
