# Generated by Django 5.0.14 on 2026-03-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_foodgroup_delete_foodcategory_food_food_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='measure_value',
        ),
    ]
