# Generated by Django 5.0.14 on 2026-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_exchangelist_exchangeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Alternatif Seçenekler'),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Alternatif Seçenekler'),
        ),
    ]
