# Generated by Django 5.0.14 on 2026-03-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_mealfood_alternative_exchanges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfood',
            name='alternative_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealrecipe',
            name='alternative_exchanges',
        ),
        migrations.CreateModel(
            name='MealFoodAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Alternatif Besin')),
                ('meal_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='diet.mealfood', verbose_name='Öğün Besini')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Alternatif Tarif')),
            ],
            options={
                'verbose_name': 'Besin Alternatifi',
                'verbose_name_plural': 'Besin Alternatifleri',
            },
        ),
        migrations.CreateModel(
            name='MealRecipeAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Alternatif Besin')),
                ('meal_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='diet.mealrecipe', verbose_name='Öğün Tarifi')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Alternatif Tarif')),
            ],
            options={
                'verbose_name': 'Tarif Alternatifi',
                'verbose_name_plural': 'Tarif Alternatifleri',
            },
        ),
    ]
