# Generated by Django 5.0.14 on 2026-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_remove_mealfood_alternative_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Ön Tanımlı (Hazır Liste) Alternatifi'),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Ön Tanımlı (Hazır Liste) Alternatifi'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='attached_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Plana Eklenecek Değişim Öğeleri (Sadece İstenenleri Seçin)'),
        ),
    ]
