# Generated by Django 5.0.14 on 2026-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_mealfood_alternative_exchanges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfood',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='protein',
        ),
        migrations.AddField(
            model_name='mealfood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Besin Özütü Seçimi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.foodgroup', verbose_name='Ait Olduğu Eşdeğer Grubu'),
        ),
    ]
