# Generated by Django 5.0.14 on 2026-03-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_remove_mealfood_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeitem',
            name='exchange_list',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealrecipe',
            name='alternative_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='alternative_exchanges',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='attached_exchanges',
        ),
        migrations.DeleteModel(
            name='ExchangeList',
        ),
        migrations.DeleteModel(
            name='ExchangeItem',
        ),
    ]
