# Generated by Django 5.0.14 on 2026-03-30 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_remove_exchangeitem_exchange_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Değişim/Alternatif Liste Adı (Örn: Ekmek Değişimleri)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Değişim/Alternatif Listesi',
                'verbose_name_plural': 'Değişim/Alternatif Listeleri',
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Besin')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Tarif')),
                ('exchange_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet.exchangelist')),
            ],
            options={
                'verbose_name': 'Değişim Öğesi',
                'verbose_name_plural': 'Değişim Öğeleri',
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='attached_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Plana Eklenecek Değişim Öğeleri (Sadece İstenenleri Seçin)'),
        ),
        migrations.AddField(
            model_name='mealfood',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Ön Tanımlı (Hazır Liste) Alternatifi'),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='alternative_exchanges',
            field=models.ManyToManyField(blank=True, to='diet.exchangeitem', verbose_name='Ön Tanımlı (Hazır Liste) Alternatifi'),
        ),
    ]
