# Generated by Django 5.0.14 on 2026-03-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_exchangelist_exchangeitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='attached_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='alternative_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealrecipe',
            name='alternative_exchanges',
        ),
    ]
