# Generated by Django 5.0.14 on 2026-03-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_dietplan_attached_exchanges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfoodalternative',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealfoodalternative',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='recipe',
        ),
        migrations.AddField(
            model_name='mealfoodalternative',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.exchangeitem', verbose_name='Alternatif (Besin veya Tarif)'),
        ),
        migrations.AddField(
            model_name='mealrecipealternative',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.exchangeitem', verbose_name='Alternatif (Besin veya Tarif)'),
        ),
    ]
