# Generated by Django 5.0.14 on 2026-03-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0014_remove_mealfoodalternative_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipe',
            name='alternative_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealfoodalternative',
            name='item',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='attached_exchanges',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='alternative_exchanges',
        ),
        migrations.AddField(
            model_name='exchangelist',
            name='foods',
            field=models.ManyToManyField(blank=True, to='diet.food', verbose_name='İçerdiği Besinler'),
        ),
        migrations.AddField(
            model_name='exchangelist',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='diet.recipe', verbose_name='İçerdiği Tarifler'),
        ),
        migrations.AddField(
            model_name='mealfoodalternative',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Alternatif Besin'),
        ),
        migrations.AddField(
            model_name='mealfoodalternative',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Alternatif Tarif'),
        ),
        migrations.AddField(
            model_name='mealrecipealternative',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Alternatif Besin'),
        ),
        migrations.AddField(
            model_name='mealrecipealternative',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Alternatif Tarif'),
        ),
        migrations.AlterField(
            model_name='exchangelist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Liste Adı (Örn: Ekmek Değişimleri)'),
        ),
        migrations.DeleteModel(
            name='ExchangeItem',
        ),
    ]
