# Generated by Django 5.0.14 on 2026-03-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diet', '0015_remove_mealrecipe_alternative_exchanges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Değişim Grubu Adı (Örn: Ekmek Grubu)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Grup Açıklaması')),
            ],
            options={
                'verbose_name': 'Değişim Grubu',
                'verbose_name_plural': 'Değişim Grupları',
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reference_quantity', models.DecimalField(decimal_places=2, default=1.0, help_text="Bu grup için '1 Değişim' karşılığı olan miktar (Örn: 100g Elma, 1 Adet Kek)", max_digits=7, verbose_name='Referans Miktar')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('food', 'recipe')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet.exchangegroup', verbose_name='Bağlı Olduğu Grup')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Grup Öğesi',
                'verbose_name_plural': 'Grup Öğeleri',
            },
        ),
        migrations.DeleteModel(
            name='ExchangeList',
        ),
    ]
