# Generated by Django 5.0.14 on 2026-03-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_exchangegroup_exchangeitem_delete_exchangelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'Besin', 'verbose_name_plural': 'Besinler'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifler'},
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Besin Seçimi'),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Tarif Seçimi'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Seçilen öğenin birimiyle otomatik eşleşir.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yağ (g/porsiyon)'),
        ),
    ]
