# Generated by Django 5.0.14 on 2026-03-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diet', '0017_alter_food_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='recipe',
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('food', 'recipe')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
