# Generated by Django 5.0.14 on 2026-03-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diet', '0018_remove_exchangeitem_food_remove_exchangeitem_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='meal_recipe',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='mealrecipealternative',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='exchangeitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.food', verbose_name='Besin Seçimi'),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.recipe', verbose_name='Tarif Seçimi'),
        ),
        migrations.CreateModel(
            name='MealAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Öğe ID')),
                ('measure_value', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ölçü Miktarı')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Öğe Tipi (Besin/Tarif)')),
                ('meal_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='diet.mealfood', verbose_name='Öğün Besini')),
                ('meal_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='diet.mealrecipe', verbose_name='Öğün Tarifi')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi')),
            ],
            options={
                'verbose_name': 'Meal Alternatifi',
                'verbose_name_plural': 'Meal Alternatifleri',
            },
        ),
        migrations.DeleteModel(
            name='MealFoodAlternative',
        ),
        migrations.DeleteModel(
            name='MealRecipeAlternative',
        ),
    ]
