# Generated by Django 5.0.14 on 2026-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_remove_mealrecipealternative_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Önerilen Tavsiye Başlığı')),
                ('content', models.TextField(verbose_name='Tavsiye İçeriği')),
            ],
            options={
                'verbose_name': 'Diyetisyen Önerisi',
                'verbose_name_plural': 'Diyetisyen Önerileri',
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='diet.dietrecommendation', verbose_name='Diyetisyen Önerileri'),
        ),
    ]
