# Generated by Django 5.0.14 on 2026-04-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0020_dietrecommendation_dietplan_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanTargetPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hedef Porsiyon')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_portions', to='diet.dietplan', verbose_name='Diyet Planı')),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.foodgroup', verbose_name='Besin Grubu')),
            ],
            options={
                'verbose_name': 'Diyet Hedef Porsiyonu',
                'verbose_name_plural': 'Diyet Hedef Porsiyonları',
            },
        ),
        migrations.CreateModel(
            name='RecipePortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Porsiyon Adedi')),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.foodgroup', verbose_name='Besin Grubu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='diet.recipe', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'Tarif Porsiyonu',
                'verbose_name_plural': 'Tarif Porsiyonları',
            },
        ),
    ]
