# Generated by Django 5.0.14 on 2026-04-03 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0021_dietplantargetportion_recipeportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ölçü Miktarı'),
        ),
    ]
