# Generated by Django 5.0.14 on 2026-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0022_recipe_measure_unit_recipe_measure_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Öğün Saati'),
        ),
    ]
