# Generated by Django 5.0.14 on 2026-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0023_meal_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='special_note',
            field=models.TextField(blank=True, null=True, verbose_name='Danışana Özel Not'),
        ),
    ]
