# Generated by Django 5.0.14 on 2026-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0024_patient_special_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öğün Saati'),
        ),
    ]
