# Generated by Django 5.0.14 on 2026-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0025_alter_meal_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğün Saati'),
        ),
    ]
