# Generated by Django 5.0.14 on 2026-04-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0026_alter_meal_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='measure_unit_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü Birimi (Örn: orta boy, adet, kase)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measure_unit_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü Birimi Yazısı'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='measure_unit_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Yazısı'),
        ),
        migrations.AlterField(
            model_name='food',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Besin Değişim Birimi (İstatistiksel)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='measure_value',
            field=models.CharField(default='1', max_length=50, verbose_name='Ölçü Miktarı (Örn: 10, 13-15, 1/4)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi (Klasik)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='measure_value',
            field=models.CharField(default='1', max_length=50, verbose_name='Ölçü Miktarı (Çarpan)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.measureunit', verbose_name='Ölçü Birimi (Klasik)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure_value',
            field=models.CharField(default='1', max_length=50, verbose_name='Hesaplama Miktarı'),
        ),
    ]
